name: CI/CD Pipeline

on:
  pull_request:
    branches: [develop, staging, main]
  push:
    branches: [develop, staging, main]

env:
  DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install -r requirements-dev.txt
      - run: ruff check . && black --check .
      - run: pytest tests/unit --cov=src

  validate:
    needs: quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@main
      - run: databricks bundle validate -t dev

  deploy:
    needs: validate
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@main
      - name: Deploy to Databricks
        run: |
          # On récupère le nom de la branche
          TARGET_ENV=${GITHUB_REF#refs/heads/}
          
          # Si la branche est 'main', la cible est 'prod'
          if [ "$TARGET_ENV" == "main" ]; then
            TARGET_ENV="prod"
          fi
          
          # Si la branche est 'develop', la cible est 'dev' (au cas où)
          if [ "$TARGET_ENV" == "develop" ]; then
            TARGET_ENV="dev"
          fi
          
          echo "Déploiement sur l'environnement : $TARGET_ENV"
          databricks bundle deploy -t $TARGET_ENV --auto-approve